site_name: Documentation
site_url: https://grzanka.github.io/mkdocs_test/
repo_url: https://github.com/grzanka/mkdocs_test
repo_name: grzanka/mkdocs_test
copyright: Copyright &copy; 2023 Leszek Grzanka


theme:
  name: material
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

nav:
- Home:
  - Overview: index.md
- Coverage report: coverage.md
- Swagger: swagger.md
- Code Reference: reference/

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- coverage:
    page_name: coverage
    html_report_dir: htmlcov
- render_swagger
- mkdocstrings:
    enable_inventory: true
    handlers:
      python:
        paths: [src]
        options:
          show_if_no_docstring: true
          line_numbers: true
          inheritance_diagram: true
          separate_signature: true
          show_root_heading: true
          show_root_members_full_path: false


